#!/usr/bin/with-contenv sh

corename=wodby
basiccoredir=/opt/solr/server/solr/configsets/basic_configs
coredir=/opt/solr/server/solr/$corename

# Initialize Solr core
if [ ! -f $coredir/core.properties ]; then
    cp -r $basiccoredir/ $coredir
    touch $coredir/core.properties

    confdir=/opt/solr_defaults/config/${WODBY_APP_TYPE}-${WODBY_APP_VERSION}

    if [ -d $confdir ]; then
        cp $confdir/* $coredir/conf
    fi

    chown -R $WODBY_USER:$WODBY_GROUP $coredir
fi
