#!/usr/bin/with-contenv sh

core_dir=/opt/solr/server/solr/default

# Initialize Solr core
if [ ! -f $core_dir/core.properties ]; then
    mkdir -p $core_dir/conf

    default_conf_dir=/opt/solr_defaults/config/${WODBY_APP_TYPE}-${WODBY_APP_VERSION}

    if [ -d $default_conf_dir ]; then
        cp $default_conf_dir/* $core_dir/conf
    else
        cp -r /opt/solr/server/solr/configsets/basic_configs/conf $core_dir
    fi

    touch $core_dir/core.properties
    chown -R $WODBY_USER:$WODBY_GROUP $core_dir
fi
